rb1:
  joint_left_velocity_controller:
#    type: velocity_controllers/JointVelocityController
    type: effort_controllers/JointEffortController
    joint: joint_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_right_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: joint_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0


